version: '3.8'

services:
  db:
    image: mysql:latest
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ip_tracker
      MYSQL_USER: bia
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 40s
      timeout: 10s
      retries: 5

  app:
    image: biamereuu/ip-tracker-server
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: bia
      DB_PASSWORD: root
      DB_NAME: ip_tracker
    ports:
      - "8080:8080"

networks:
  mynetwork:
    driver: bridge